language: haxe
haxe:
  - "3.2.1"
  - development

install:
  - haxelib dev quick-haxe $TRAVIS_BUILD_DIR
  - haxelib install openfl
  - haxelib install hamcrest
  - haxelib list

script:
  - cd tests
  - haxe test.hxml
  - neko tests.n

cache:
  directories:
    - $HOME/haxe/lib
