language: haxe
haxe:
  - "3.1.3"
  - development
  
install:
  - haxelib install munit
  - haxelib install hamcrest

before_script:
  - cd $TRAVIS_BUILD_DIR
  - haxelib run munit config -hxml test.hxml
  
script:
  - haxelib run munit test